#!/bin/bash

# 🚀 Quick Commands Reference
# Save this for easy access to common commands

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📖 PORTFOLIO COMMANDS QUICK REFERENCE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🚀 GETTING STARTED"
echo "  Clone repo:        git clone https://github.com/msapuan/msapuan.github.io.git"
echo "  Navigate:          cd msapuan.github.io"
echo "  Install deps:      bundle install"
echo "  Start server:      bundle exec jekyll serve --livereload"
echo "  Open browser:      http://localhost:4000"
echo ""

echo "📝 BLOG OPERATIONS"
echo "  Create post:       touch _posts/YYYY-MM-DD-title.md"
echo "  Format example:    _posts/2025-01-15-my-first-post.md"
echo "  Front matter:      See PANDUAN_LENGKAP.md for template"
echo ""

echo "🎨 CUSTOMIZATION"
echo "  Edit colors:       vim _data/colors.json"
echo "  Edit typing:       vim assets/js/typing.js"
echo "  Edit footer:       vim _includes/footer.html"
echo "  Edit config:       vim _config.yml"
echo ""

echo "🔧 DEVELOPMENT"
echo "  Build site:        bundle exec jekyll build"
echo "  Clear cache:       rm -rf .jekyll-cache _site"
echo "  Restart server:    (Ctrl+C) then jekyll serve"
echo "  Port change:       jekyll serve --port 5000"
echo ""

echo "📤 GIT & DEPLOYMENT"
echo "  Stage changes:     git add ."
echo "  Commit:            git commit -m 'Your message'"
echo "  Push to main:      git push origin main"
echo "  View status:       git status"
echo "  Check log:         git log --oneline -10"
echo ""

echo "🔍 CHECKING"
echo "  Gems list:         bundle list"
echo "  Jekyll version:    jekyll --version"
echo "  Ruby version:      ruby --version"
echo "  Build dry-run:     jekyll build --dry-run"
echo ""

echo "📚 DOCUMENTATION"
echo "  Setup guide:       cat SETUP_GUIDE.md"
echo "  Full guide:        cat PANDUAN_LENGKAP.md"
echo "  Checklist:         bash CHECKLIST.sh"
echo "  Summary:           cat IMPLEMENTATION_SUMMARY.md"
echo ""

echo "🌐 URLS"
echo "  Local dev:         http://localhost:4000"
echo "  Live site:         https://yourusername.github.io"
echo "  Blog:              https://yourusername.github.io/blog/"
echo "  Projects:          https://yourusername.github.io/projects/"
echo ""

echo "🎯 FIRST TIME SETUP"
echo "  1. git clone ..."
echo "  2. cd msapuan.github.io"
echo "  3. bundle install"
echo "  4. Edit _config.yml"
echo "  5. bundle exec jekyll serve"
echo "  6. Open http://localhost:4000"
echo "  7. Test locally"
echo "  8. git add . && git commit -m 'Setup' && git push origin main"
echo "  9. Wait 1-2 min for deployment"
echo "  10. Visit https://yourusername.github.io 🎉"
echo ""

echo "💡 TIPS"
echo "  • Always test locally before pushing"
echo "  • Use --livereload untuk auto-refresh"
echo "  • Keep _config.yml updated"
echo "  • Write meaningful git commit messages"
echo "  • Check GitHub Actions for deployment status"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "For more details, read SETUP_GUIDE.md or PANDUAN_LENGKAP.md"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
